accounts/urls.py
from django.urls import path
from . import views

app_name="accounts"

urlpatterns = [
    path("signup",views.SignUp,name="signup"),
    path("profile/",views.My_Profile,name="profile"),
    path("profile/edit",views.Edit_My_Profile,name="edit_my_profile"),
    path("pass_change/",views.Change_Password,name="change_password"),
] 

home/urls.py
from django.urls import path
from . import views

app_name="home"

urlpatterns = [
    path("",views.home_page,name="home_page"),
    path('students/' , views.students_information , name= 'students') ,
    path("students_create/" , views.students_create, name= 'students_create') ,
    
    path("students_detail/<str:slug>" , views.students_details, name= 'students_detail') ,
    path("students_delete/<str:slug>" , views.students_delete, name= 'students_delete') ,
    path('edit/<str:slug>' , views.students_edit , name= 'student_edit') ,

] 

project/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include ('accounts.urls' , namespace='accounts')),
    path('admin/', admin.site.urls),
    path('', include ('home.urls' , namespace='home')),

]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django .contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save

class Profile(models.Model):
    user=models.OneToOneField(User , on_delete=models.CASCADE)
    address = models.CharField(help_text = "text",max_length = 150)
    phone=models.IntegerField(default=1)
    

    def __str__(self)  :
        return str (self.user)
    

        
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)        
        

home/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User

# Create your models here.
class Students(models.Model):
    STUDENTS_CLASS = (
        ('10 a','10 a'),
        ('10 b','10 b'),
    )
    
    student_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length = 150)
    student_class=models.CharField(choices=STUDENTS_CLASS, max_length=50)
    mobile_number=models.CharField(max_length=10)
    address = models.CharField(max_length = 150)
    img=models.ImageField(upload_to='image_student')
    slug=models.SlugField(blank=True ,null=True)

    
    
    def save(self,*args,**kwargs):
        self.slug=slugify(self.name)
        super(Students,self).save(*args,**kwargs)
 
    
    def __str__(self):
        return self.name

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from . models import Profile

class SignUpForms(UserCreationForm):
    class Meta:
        model=User
        fields=['username','email','password1','password2']
        




class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields=['username','first_name','last_name',]
        
        
class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields=['address','phone']

home/forms.py
from django import forms
from .models import Students

class Students_form(forms.ModelForm):
    class Meta :
        model=Students
        fields="__all__"
        exclude=('slug',)

accounts/views.py
from django.shortcuts import render , redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import PasswordChangeForm
from . models import Profile 
from . forms import SignUpForms ,UserForm , ProfileForm 
# from django.contrib.auth import update_session_auth_hash
# from django.contrib import messages



def SignUp(requset):
    if requset.method == 'POST':
        form=SignUpForms(requset.POST)
        if form.is_valid():
            form.save()
            username=form.cleaned_data['username']
            password=form.cleaned_data['password1']
            user=authenticate(username=username , password=password )
            login(requset,user)
        return redirect("/")
        
    else:
        form=SignUpForms()
    return render(requset , 'registration/signup.html',{'form':form})




def My_Profile(requset):
    my_profile=Profile.objects.get(user=requset.user)
    return render(requset , 'profile/profile.html',{'my_profile':my_profile})


def Edit_My_Profile(requset):
    profile = Profile.objects.get(user=requset.user)
    if requset.method == 'POST':
        userform=UserForm(requset.POST , instance=requset.user)
        profileform=ProfileForm(requset.POST , instance=profile)
        if userform.is_valid() and profileform.is_valid():
            userform.save()
            profileform.save(commit=False)
            profileform.user=requset.user
            profileform.save()
            return redirect("/accounts/profile")
        
    else:
        userform=UserForm(instance=requset.user)
        profileform=ProfileForm(instance=profile)
    return render(requset , 'profile/edit_profile.html', {'userform':userform ,'profileform':profileform })



def Change_Password(requset):
    if requset.method == 'POST':
        password_form = PasswordChangeForm(requset.user,requset.POST)
        if password_form.is_valid():
            password_form.save()
            return redirect('/accounts/password_change/done')
    else:
        password_form = PasswordChangeForm(requset.user)
        # messages.error(requset, 'Please correct the error below.')
        
    return render(requset ,'registration/password_change.html',{'password_form':password_form})

home/views.py
from django.shortcuts import render , redirect
from .models import Students
from .forms import Students_form

def home_page(requset):
    return render (requset , 'home/home_page.html')


def students_information(requset):
    students = Students.objects.all()
    context={'students':students}
    return render(requset , "students/students.html" , context)


def students_details(requset , slug):
    students_detail = Students.objects.get(slug = slug)
    context={'students_detail': students_detail}
    return render(requset , "students/students_details.html" , context)

# CRUD
def students_edit(requset , slug):
    student_edit = Students.objects.get(slug = slug)
    if requset.method == 'POST':
        edit=Students_form(requset.POST, requset.FILES, instance=student_edit)
        if edit.is_valid():
            edit.save()
            return redirect("/")
    else:
        edit=Students_form(instance=student_edit)

    context={'edit': edit}
    return render(requset , "students/students_edit.html" , context)


def students_delete(requset , slug):
    student_delete = Students.objects.get(slug = slug)
    if requset.method == 'POST':
            student_delete.delete()
            return redirect("/students")

    return render(requset , "students/students_delete.html" )


def students_create(requset):
    if requset.method == 'POST':
        create = Students_form(requset.POST, requset.FILES, )
        if create.is_valid():
            create.save()
            return redirect('/students')
    else:
        create = Students_form()
    context={'create':create}
    return render(requset , 'students/students_create.html' , context)
        

accounts/templates/profile/edit_profile.html
{% extends "base.html" %} {% load bootstrap4 %} 

{% block body %}
<div class="page-wrapper">
  <div class="content container-fluid">
      <form method="POST" enctype="multipart/form-data">
        {% csrf_token %} 
        {% bootstrap_form userform %}
         {% bootstrap_form profileform %} 
         {% buttons %}
        <button class="btn btn-primary boxed-btn3 w-50" type="submit">
          Apply Now
        </button>
        {% endbuttons %}
      </form>
  </div>
</div>
{% endblock body %}
  

accounts/templates/profile/profile.html
good

home/templates/include/footer.html
{% load static %}

<footer>
    <p>Copyright © 2020 Dreamguys.</p>
 </footer>

home/templates/include/header.html
{% load static %}

<div class="header">
    <div class="header-left">
       <a href="index.html" class="logo">
       <img src="{% static 'assets/img/logo.png' %}" alt="Logo">
       </a>
       <a href="index.html" class="logo logo-small">
       <img src="{% static 'assets/img/logo-small.png' %}" alt="Logo" width="30" height="30">
       </a>
    </div>
    <a href="javascript:void(0);" id="toggle_btn">
    <i class="fas fa-align-left"></i>
    </a>
    <div class="top-nav-search">
       <form>
          <input type="text" class="form-control" placeholder="Search here">
          <button class="btn" type="submit"><i class="fas fa-search"></i></button>
       </form>
    </div>
    <a class="mobile_btn" id="mobile_btn">
    <i class="fas fa-bars"></i>
    </a>
    <ul class="nav user-menu">
       <li class="nav-item dropdown noti-dropdown">
          <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
          <i class="far fa-bell"></i> <span class="badge badge-pill">3</span>
          </a>
          <div class="dropdown-menu notifications">
             <div class="topnav-dropdown-header">
                <span class="notification-title">Notifications</span>
                <a href="javascript:void(0)" class="clear-noti"> Clear All </a>
             </div>
             <div class="noti-content">
                <ul class="notification-list">
                   <li class="notification-message">
                      <a href="#">
                         <div class="media">
                            <span class="avatar avatar-sm">
                            <img class="avatar-img rounded-circle" alt="User Image" src="{% static 'assets/img/profiles/avatar-02.jpg' %}">
                            </span>
                            <div class="media-body">
                               <p class="noti-details"><span class="noti-title">Carlson Tech</span> has approved <span class="noti-title">your estimate</span></p>
                               <p class="noti-time"><span class="notification-time">4 mins ago</span></p>
                            </div>
                         </div>
                      </a>
                   </li>
                   <li class="notification-message">
                      <a href="#">
                         <div class="media">
                            <span class="avatar avatar-sm">
                            <img class="avatar-img rounded-circle" alt="User Image" src="{% static 'assets/img/profiles/avatar-11.jpg' %}">
                            </span>
                            <div class="media-body">
                               <p class="noti-details"><span class="noti-title">International Software Inc</span> has sent you a invoice in the amount of <span class="noti-title">$218</span></p>
                               <p class="noti-time"><span class="notification-time">6 mins ago</span></p>
                            </div>
                         </div>
                      </a>
                   </li>
                   <li class="notification-message">
                      <a href="#">
                         <div class="media">
                            <span class="avatar avatar-sm">
                            <img class="avatar-img rounded-circle" alt="User Image" src="{% static 'assets/img/profiles/avatar-17.jpg' %}">
                            </span>
                            <div class="media-body">
                               <p class="noti-details"><span class="noti-title">John Hendry</span> sent a cancellation request <span class="noti-title">Apple iPhone XR</span></p>
                               <p class="noti-time"><span class="notification-time">8 mins ago</span></p>
                            </div>
                         </div>
                      </a>
                   </li>
                   <li class="notification-message">
                      <a href="#">
                         <div class="media">
                            <span class="avatar avatar-sm">
                            <img class="avatar-img rounded-circle" alt="User Image" src="{% static 'assets/img/profiles/avatar-13.jpg' %}">
                            </span>
                            <div class="media-body">
                               <p class="noti-details"><span class="noti-title">Mercury Software Inc</span> added a new product <span class="noti-title">Apple MacBook Pro</span></p>
                               <p class="noti-time"><span class="notification-time">12 mins ago</span></p>
                            </div>
                         </div>
                      </a>
                   </li>
                </ul>
             </div>
             <div class="topnav-dropdown-footer">
                <a href="#">View all Notifications</a>
             </div>
          </div>
       </li>
       <li class="nav-item dropdown has-arrow">
          <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
          <span class="user-img"><img class="rounded-circle" src="{{user.profile_pic.url}}" width="31" alt="Ryan Taylor"></span>
          </a>
          <div class="dropdown-menu">
             <div class="user-header">
                <div class="avatar avatar-sm">
                   <img src="{{user.profile_pic.url}}" alt="User Image" class="avatar-img rounded-circle">
                </div>
                <div class="user-text">
                   <h6>{{user.first_name}} {{user.last_name}}</h6>

                   {% if user.user_type == 'HOD' %}
                   <p class="text-muted mb-0">Hod of Department</p>

                   {% elif user.user_type == 'Staff' %}
                   <p class="text-muted mb-0">staff</p>

                   {% else %}
                   <p class="text-muted mb-0">Student</p>
                   
                   {% endif %}

                </div>
             </div>
             {% comment %} <a class="dropdown-item" href="{% url 'Profile' %}">My Profile</a> {% endcomment %}
             <a class="dropdown-item" href="inbox.html">Inbox</a>
              {% comment %}<a class="dropdown-item" href="{% url 'Logout' %}">Logout</a> {% endcomment %}
          </div>
       </li>
    </ul>
</div>

home/templates/include/sidebar.html
{% load static %}

<div class="sidebar" id="sidebar">
    <div class="sidebar-inner slimscroll">
       <div id="sidebar-menu" class="sidebar-menu">
          <ul>
             <li class="menu-title">
                <span>Main Menu</span>
             </li>
             <li>
               <a href="holiday.html"><i class="fas fa-holly-berry"></i> <span>Dashboard</span></a>
            </li>
             <li class="submenu">
                <a href="#"><i class="fas fa-user-graduate"></i> <span> Students</span> <span class="menu-arrow"></span></a>
                <ul>
                   <li><a href="{% url 'home:students' %}">Student List</a></li>
                   <li><a href="student-details.html">Student View</a></li>
                   <li><a href="add-student.html">Student Add</a></li>
                   <li><a href="edit-student.html">Student Edit</a></li>
                </ul>
             </li>
             <li class="submenu">
                <a href="#"><i class="fas fa-chalkboard-teacher"></i> <span> staff</span> <span class="menu-arrow"></span></a>
                <ul>
                   <li><a href="teachers.html">Teacher List</a></li>
                   <li><a href="teacher-details.html">Teacher View</a></li>
                   <li><a href="add-teacher.html">Teacher Add</a></li>
                   <li><a href="edit-teacher.html">Teacher Edit</a></li>
                </ul>
             </li>
             <li class="submenu">
                <a href="#"><i class="fa fa-graduation-cap"></i> <span> Course</span> <span class="menu-arrow"></span></a>
                <ul>
                   <li><a href="departments.html">Department List</a></li>
                   <li><a href="add-department.html">Department Add</a></li>
                   <li><a href="edit-department.html">Department Edit</a></li>
                </ul>
             </li>
             <li class="submenu">
                <a href="#"><i class="fas fa-book-reader"></i> <span> Subjects</span> <span class="menu-arrow"></span></a>
                <ul>
                   <li><a href="subjects.html">Subject List</a></li>
                   <li><a href="add-subject.html">Subject Add</a></li>
                   <li><a href="edit-subject.html">Subject Edit</a></li>
                </ul>
             </li>
          
             <li class="submenu">
                <a href="#"><i class="fas fa-file-invoice-dollar"></i> <span>Session</span> <span class="menu-arrow"></span></a>
                <ul>
                   <li><a href="fees-collections.html">Fees Collection</a></li>
                   <li><a href="expenses.html">Expenses</a></li>
                   <li><a href="salary.html">Salary</a></li>
                   <li><a href="add-fees-collection.html">Add Fees</a></li>
                   <li><a href="add-expenses.html">Add Expenses</a></li>
                   <li><a href="add-salary.html">Add Salary</a></li>
                </ul>
             </li>
             <li>
                <a href="holiday.html"><i class="fas fa-holly-berry"></i> <span>view Attendance </span></a>
             </li>
             <li>
                <a href="fees.html"><i class="fas fa-comment-dollar"></i> <span>Staff Feedback</span></a>
             </li>
             <li>
                <a href="exam.html"><i class="fas fa-clipboard-list"></i> <span>Student Feedback</span></a>
             </li>
             <li>
                <a href="event.html"><i class="fas fa-calendar-day"></i> <span>Staff Leave</span></a>
             </li>
             <li>
                <a href="time-table.html"><i class="fas fa-table"></i> <span>Student Leave</span></a>
             </li>
             <li>
                {% comment %} <a href="{% url 'Logout' %}"><i class="fas fa-sign-out"></i> <span>Logout</span></a> {% endcomment %}
             </li>
          </ul>
       </div>
    </div>
</div>

home/templates/students/students.html
{% extends "base.html" %}
{% block body %}
<div class="page-wrapper">
    <div class="content container-fluid">
       <div class="page-header">
          <div class="row align-items-center">
             <div class="col">
                <h3 class="page-title">Students</h3>
                <ul class="breadcrumb">
                   <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
                   <li class="breadcrumb-item active">Students</li>
                </ul>
             </div>
             <div class="col-auto text-right float-right ml-auto">
                <a href="#" class="btn btn-outline-primary mr-2"><i class="fas fa-download"></i> Download</a>
                <a href="{% url 'home:students_create' %}" class="btn btn-primary"><i class="fas fa-plus"></i></a>
             </div>
          </div>
       </div>
       <div class="row">
          <div class="col-sm-12">
             <div class="card card-table">
                <div class="card-body">
                   <div class="table-responsive">
                      <table class="table table-hover table-center mb-0 datatable">
                         <thead>
                            <tr>
                               <th>ID</th>
                               <th>Name</th>
                               <th>Class</th>
                               <th>DOB</th>
                               <th>Parent Name</th>
                               <th>Mobile Number</th>
                               <th>Address</th>
                               <th class="text-right">Action</th>
                            </tr>
                         </thead>
                         <tbody>
                           
                           {% for student in students  %}
                            <tr>
                               <td>{{student.student_id}}</td>
                               <td>
                                  <h2 class="table-avatar">
                                     <a href="student-details.html" class="avatar avatar-sm mr-2"><img class="avatar-img rounded-circle" src="{{student.img.url}}" alt="User Image"></a>
                                     <a href="{% url 'home:students_detail' student.slug %}">{{student.name}}</a>
                                  </h2>
                               </td>
                               <td>{{student.student_class}}</td>
                               <td>26 Apr 1994</td>
                               <td>Stephen Marley</td>
                               <td>077 3499 9959</td>
                               <td>86 Lamphey Road, Thelnetham</td>
                               <td class="text-right">


                                 <div class="actions">
                                    <a href="{% url 'home:students_detail' student.slug %}" class="btn btn-sm btn btn-primary mr-2">
                                       <i class="fa fa-eye"></i>
                                    </a>
                                    <a href="{% url 'home:student_edit' student.slug %}" class="btn btn-sm bg-success-light mr-2">
                                       <i class="fas fa-pen"></i>
                                    </a>
                                    <a href="{% url 'home:students_delete' student.slug %}" class="btn btn-sm bg-danger-light">
                                       <i class="fas fa-trash"></i>
                                    </a>
                                 </div>

                               </td>
                            </tr>
                            {% endfor %}


                         </tbody>
                      </table>
                   </div>
                </div>
             </div>
          </div>
       </div>
    </div>
    <footer>
       <p>Copyright © 2020 Dreamguys.</p>
    </footer>
 </div>
{% endblock body %}

home/templates/students/students_create.html
{% extends "base.html" %} 
{% load bootstrap4 %} 

{% block body %}
<div class="page-wrapper">
  <div class="content container-fluid">
      <form method="POST" enctype="multipart/form-data">
        {% csrf_token %} 
        {% bootstrap_form create %}
         {% buttons %}
        <button class="btn btn-primary boxed-btn3 w-50" type="submit">
          Apply Now
        </button>
        {% endbuttons %}
      </form>
  </div>
</div>
{% endblock body %}
  

home/templates/students/students_delete.html
{% extends "base.html" %} 
{% load bootstrap4 %} 

{% block body %}
<div class="page-wrapper">
  <div class="content container-fluid">
    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="alert alert-danger" role="alert">
        Do you really want to delete this item?
      </div>
      <div class="text-center">
        <a href="{% url 'home:students' %}" type="button" class="btn btn-success m-l-5">
          <i class="far fa-save m-r-5"></i> <span>Draft</span>
        </a>
        <button class="btn btn-danger m-l-5" type="submit"> <i class="far fa-trash-alt m-r-5"></i><span>Delete</span></button>
        </div>
    </form>
  </div>
</div>
{% endblock body %}
  

home/templates/students/students_details.html
{% extends "base.html" %}

{% block body %}
<div class="page-wrapper">
    <div class="content container-fluid">
       <div class="page-header">
          <div class="row">
             <div class="col">
                <h3 class="page-title">Profile</h3>
                <ul class="breadcrumb">
                   <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
                   <li class="breadcrumb-item active">Profile</li>
                </ul>
             </div>
          </div>
       </div>
       <div class="row">
          <div class="col-md-12">
             <div class="profile-header">
                <div class="row align-items-center">
                   <div class="col-auto profile-image">
                      <a href="#">
                      <img class="rounded-circle" alt="User Image" src="{{students_detail.img.url}}">
                      </a>
                   </div>
                   <div class="col ml-md-n2 profile-user-info">
                      <h4 class="user-name mb-0">{{students_detail.name}}</h4>
                      <h6 class="text-muted">UI/UX Design Team</h6>
                      <div class="user-Location"><i class="fas fa-map-marker-alt"></i> Florida, United States</div>
                      <div class="about-text">Lorem ipsum dolor sit amet.</div>
                   </div>
                   <div class="col-auto profile-btn">
                      <a href="{% url 'home:student_edit' students_detail.slug %}" class="btn btn-primary">
                      Edit
                      </a>
                   </div>
                </div>
             </div>
             <div class="profile-menu">
                <ul class="nav nav-tabs nav-tabs-solid">
                   <li class="nav-item">
                      <a class="nav-link active" data-toggle="tab" href="#per_details_tab">About</a>
                   </li>
                   <li class="nav-item">
                      <a class="nav-link" data-toggle="tab" href="#password_tab">Password</a>
                   </li>
                </ul>
             </div>
             <div class="tab-content profile-tab-cont">
                <div class="tab-pane fade show active" id="per_details_tab">
                   <div class="row">
                      <div class="col-lg-9">
                         <div class="card">
                            <div class="card-body">
                               <h5 class="card-title d-flex justify-content-between">
                                  <span>Personal Details</span>
                                  <a class="edit-link" data-toggle="modal" href="#edit_personal_details"><i class="far fa-edit mr-1"></i>Edit</a>
                               </h5>
                               <div class="row">
                                  <p class="col-sm-3 text-muted text-sm-right mb-0 mb-sm-3">Name</p>
                                  <p class="col-sm-9">John Doe</p>
                               </div>
                               <div class="row">
                                  <p class="col-sm-3 text-muted text-sm-right mb-0 mb-sm-3">Date of Birth</p>
                                  <p class="col-sm-9">24 Jul 1983</p>
                               </div>
                               <div class="row">
                                  <p class="col-sm-3 text-muted text-sm-right mb-0 mb-sm-3">Email ID</p>
                                  <p class="col-sm-9"><a href="https://preschool.dreamguystech.com/cdn-cgi/l/email-protection" class="__cf_email__" data-cfemail="711b1e191f151e14311409101c011d145f121e1c">[email&#160;protected]</a></p>
                               </div>
                               <div class="row">
                                  <p class="col-sm-3 text-muted text-sm-right mb-0 mb-sm-3">Mobile</p>
                                  <p class="col-sm-9">305-310-5857</p>
                               </div>
                               <div class="row">
                                  <p class="col-sm-3 text-muted text-sm-right mb-0">Address</p>
                                  <p class="col-sm-9 mb-0">4663 Agriculture Lane,<br>
                                     Miami,<br>
                                     Florida - 33165,<br>
                                     United States.
                                  </p>
                               </div>
                            </div>
                         </div>
                      </div>
                      <div class="col-lg-3">
                         <div class="card">
                            <div class="card-body">
                               <h5 class="card-title d-flex justify-content-between">
                                  <span>Account Status</span>
                                  <a class="edit-link" href=""><i class="far fa-edit mr-1"></i> Edit</a>
                               </h5>
                               <button class="btn btn-success" type="button"><i class="fe fe-check-verified"></i> Active</button>
                            </div>
                         </div>
                         <div class="card">
                            <div class="card-body">
                               <h5 class="card-title d-flex justify-content-between">
                                  <span>Skills </span>
                                  <a class="edit-link" href="#"><i class="far fa-edit mr-1"></i> Edit</a>
                               </h5>
                               <div class="skill-tags">
                                  <span>Html5</span>
                                  <span>CSS3</span>
                                  <span>WordPress</span>
                                  <span>Javascript</span>
                                  <span>Android</span>
                                  <span>iOS</span>
                                  <span>Angular</span>
                                  <span>PHP</span>
                               </div>
                            </div>
                         </div>
                      </div>
                   </div>
                </div>
                <div id="password_tab" class="tab-pane fade">
                   <div class="card">
                      <div class="card-body">
                         <h5 class="card-title">Change Password</h5>
                         <div class="row">
                            <div class="col-md-10 col-lg-6">
                               <form>
                                  <div class="form-group">
                                     <label>Old Password</label>
                                     <input type="password" class="form-control">
                                  </div>
                                  <div class="form-group">
                                     <label>New Password</label>
                                     <input type="password" class="form-control">
                                  </div>
                                  <div class="form-group">
                                     <label>Confirm Password</label>
                                     <input type="password" class="form-control">
                                  </div>
                                  <button class="btn btn-primary" type="submit">Save Changes</button>
                               </form>
                            </div>
                         </div>
                      </div>
                   </div>
                </div>
             </div>
          </div>
       </div>
    </div>
 </div>
{% endblock body %}